export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    home: '/dashboard/home',
    usa: '/dashboard/usa',
    india: '/dashboard/india',
    account: '/dashboard/account',
    settings: '/dashboard/settings',
    positions: '/dashboard/positions',
    orders: '/dashboard/orders',
    transactions: '/dashboard/transactions',
    shortable: '/dashboard/shortable',
    watchlists: '/dashboard/watchlists',
    screeners: '/dashboard/screeners',
    chart: '/dashboard/chart',
    news: '/dashboard/news',
    calendar: '/dashboard/calendar',
    risk: '/dashboard/risk',
    alerts: '/dashboard/alerts',
    calculators: '/dashboard/calculators',
    help: '/dashboard/help',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
