name: Prod deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events, but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'uikit/tailwind/**'
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: 🎉 Prod Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@v4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          SOURCE: 'uikit/tailwind/dist/'
          REMOTE_HOST: 145.79.3.173
          REMOTE_USER: u965251139
          REMOTE_PORT: "65002"
          TARGET: domains/tailwind.saasable.io/public_html/free
          EXCLUDE: '/node_modules/'
